module.exports = {
  expectResultsCompare: [
    {
      id: 1,
      arrayA: ["dog", "cat", "rat", "fox", "frog", "dinosaur", "cow", "bull"],
      arrayB: [
        "dog",
        "dog",
        "cat",
        "dog",
        "frog",
        "rat",
        "turtle",
        "fox",
        "fox",
        "man",
        "man",
        "frog",
        "man",
      ],
      duplicatedValues: {
        dog: 3,
        cat: 1,
        rat: 1,
        frog: 2,
        fox: 2,
      },
    },
    {
      id: 2,
      arrayA: ["dog", "cat", "rat", "fox", "frog", "dinosaur", "cow", "bull"],
      arrayB: [
        "parrot",
        "parrot",
        "kitten",
        "parrot",
        "pig",
        "mouse",
        "turtle",
        "hamster",
        "hamster",
        "man",
        "man",
        "pig",
        "man",
      ],
      duplicatedValues: {},
    },
    {
      id: 3,
      arrayA: ["dog", "cat", "rat", "fox", "man", "dinosaur", "cow", "bull"],
      arrayB: [
        "parrot",
        "parrot",
        "kitten",
        "parrot",
        "pig",
        "mouse",
        "turtle",
        "hamster",
        "hamster",
        "man",
        "man",
        "pig",
        "man",
      ],
      duplicatedValues: {
        man: 3,
      },
    },
    {
      id: 4,
      arrayA: [
        "dog",
        "cat",
        "rat",
        "fox",
        "hamster",
        "dinosaur",
        "cow",
        "bull",
      ],
      arrayB: [
        "parrot",
        "parrot",
        "kitten",
        "parrot",
        "pig",
        "mouse",
        "turtle",
        "hamster",
        "hamster",
        "man",
        "man",
        "pig",
        "man",
      ],
      duplicatedValues: {
        hamster: 2,
      },
    },
  ],
};
